name: mededit
target_size: &target_size !!python/tuple [128, 128, 128]
train_batch_size: &tbatch_size 10
checkpoint_path: &checkpoint_path './projects/3dmededit/weights/runs/'
seed: 2109
#
# Experiment
#
experiment:
  name: vqvae_evaluation
  task: evaluation
  weights: projects/3dmededit/weights/runs/2025_01_10_11_52_32_286429/best_epoch_785.pt
  
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.vqvae
  class_name: VQVAE
  params:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    num_res_channels: 2
    num_channels: 
      - 96
      - 192
    upsample_parameters:
      - [2, 4, 1, 1, 0]
      - [2, 4, 1, 1, 0]
      # - [2, 4, 1, 1, 0]
    # output_act: 'sigmoid'
    downsample_parameters:
      - [2, 4, 1, 1]
      - [2, 4, 1, 1]
      # - [2, 4, 1, 1, 0]

trainer:

downstream_tasks:
  evaluation:
    module_name: projects.3dmededit.evaluator
    class_name: AutoencodeEvaluator
    checkpoint_path: *checkpoint_path
    data_loader:
      module_name: data.loaders.atlas_3d_loader
      class_name: Atlas3DLoader
      datasets:
        - atlas
      params:
        args:
          target_size: *target_size
          batch_size: *tbatch_size
          dataset_module:
            module_name: data.loaders.atlas_3d_loader
            class_name: Atlas3DDataset
          data_dir:
            test:
              # - './data/atlas_3d_splits/atlas_3d_test.csv'
              - './data/atlas_skull_stripped/atlas_skull_stripped_test.csv'
              - './data/ixi_skull_stripped/ixi_test.csv'
